import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { Application, SavedSearch } from "./data";

export type ViewId = "dashboard" | "search" | "opportunities" | "applications" | "coach" | "cv" | "market" | "learn" | "saved" | "profile" | "admin";
export type User = { name: string; email: string; password: string; title: string; location: string; about: string; skills: string[]; isAdmin?: boolean; targetRoles?: string[]; targetCountries?: string[]; salaryGoal?: string; remotePreference?: "Remote" | "Hybrid" | "On-site" | "Any"; careerGoal?: string; visaStatus?: string; languages?: string[]; certifications?: string[]; achievements?: string[]; blockedCompanies?: string[]; recruiterVisibility?: "visible" | "anonymous" | "hidden"; stealthMode?: boolean };
type Filters = { role: string; function: string; industry: string; location: string };
type CareerSignal = { id: string; title: string; description: string; priority: "high" | "medium" | "low"; createdAt: string };
type HuntAction = { id: string; title: string; description: string; view: ViewId; completed: boolean };
export type Referral = { id: string; jobId: string; note: string; status: "requested" | "offered" | "connected"; createdAt: string };
export type MentorRequest = { id: string; goal: string; status: "open" | "matched" | "closed"; createdAt: string };
export type CareerCircle = { id: string; name: string; focus: string; members: number };
type State = { users: User[]; sessionEmail: string | null; view: ViewId; filters: Filters; applications: Application[]; savedJobIds: string[]; savedSearches: SavedSearch[]; demoOpen: boolean; adminPrompt: boolean; cvText: string; huntMode: boolean; careerSignals: CareerSignal[]; huntActions: HuntAction[]; careerGoalDraft: string; referrals: Referral[]; mentorRequests: MentorRequest[]; careerCircles: CareerCircle[]; lastAgentRunAt: string | null;
  register: (u: Omit<User, "isAdmin">) => { ok: boolean; error?: string }; login: (email: string, password: string) => { ok: boolean; error?: string }; logout: () => void; setView: (v: ViewId) => void; setFilters: (f: Partial<Filters>) => void; applyTo: (jobId: string) => void; setStatus: (id: string, status: Application["status"]) => void; toggleSaveJob: (jobId: string) => void; saveCurrentSearch: () => void; removeSavedSearch: (id: string) => void; updateProfile: (p: Partial<User>) => void; setDemoOpen: (v: boolean) => void; setAdminPrompt: (v: boolean) => void; setCvText: (v: string) => void; setHuntMode: (v: boolean) => void; completeHuntAction: (id: string) => void; addCareerSignal: (s: Omit<CareerSignal, "id" | "createdAt">) => void; setCareerGoalDraft: (v: string) => void; requestReferral: (jobId: string, note: string) => void; requestMentor: (goal: string) => void; setAgentRun: () => void };

const SEED_USERS: User[] = [
  { name: "Alex Rivera", email: "demo@gotecha.com", password: "huntends", title: "Product Manager", location: "Bangalore, India", about: "Product leader focused on payments, marketplace growth, and AI-assisted workflows. 8 years shipping 0–1 and scale products.", skills: ["Product Strategy", "Analytics", "Stakeholder Mgmt", "Payments"], targetRoles: ["Senior Product Manager"], targetCountries: ["India", "Singapore"], salaryGoal: "₹50L+", remotePreference: "Hybrid", careerGoal: "Move into a global product leadership role.", visaStatus: "India work authorization", languages: ["English", "Hindi"], recruiterVisibility: "visible", stealthMode: false, blockedCompanies: [] },
  { name: "Gotcha Admin", email: "admin@gotecha.com", password: "adminhunt", title: "Platform Administrator", location: "Global", about: "Administrator access for Gotcha operations.", skills: ["Operations"], isAdmin: true },
];
const DEFAULT_ACTIONS: HuntAction[] = [
  { id: "discover", title: "Review top opportunities", description: "Review the highest-fit roles before they go stale.", view: "opportunities", completed: false },
  { id: "apply", title: "Send one quality application", description: "Tailor your CV and apply to your strongest match.", view: "search", completed: false },
  { id: "prepare", title: "Prepare for interviews", description: "Use AI Career Coach to rehearse your next conversation.", view: "coach", completed: false },
  { id: "skill", title: "Close one skill gap", description: "Use Learning Center to improve market competitiveness.", view: "learn", completed: false },
];

export const useGotcha = create<State>()(persist((set, get) => ({
  users: SEED_USERS, sessionEmail: null, view: "dashboard", filters: { role: "Product Manager", function: "Technology", industry: "FinTech", location: "India / Remote" },
  applications: [
    { id: "a1", jobId: "j1", status: "applied", appliedAt: "2026-08-12" }, { id: "a2", jobId: "j2", status: "interview", appliedAt: "2026-08-08" }, { id: "a3", jobId: "j4", status: "assessment", appliedAt: "2026-08-04" }, { id: "a4", jobId: "j10", status: "offer", appliedAt: "2026-07-28" }, { id: "a5", jobId: "j8", status: "rejected", appliedAt: "2026-07-20" }, { id: "a6", jobId: "j5", status: "applied", appliedAt: "2026-08-18" }, { id: "a7", jobId: "j6", status: "interview", appliedAt: "2026-08-15" }, { id: "a8", jobId: "j3", status: "applied", appliedAt: "2026-08-21" }, { id: "a9", jobId: "j7", status: "applied", appliedAt: "2026-08-10" }, { id: "a10", jobId: "j11", status: "interview", appliedAt: "2026-08-06" }, { id: "a11", jobId: "j12", status: "applied", appliedAt: "2026-08-02" }, { id: "a12", jobId: "j9", status: "applied", appliedAt: "2026-07-30" },
  ],
  savedJobIds: ["j1", "j2", "j3"], savedSearches: [{ id: "s1", query: "Product Manager FinTech India", role: "Product Manager", function: "Product", industry: "FinTech", location: "India / Remote", createdAt: "2026-08-20" }], demoOpen: false, adminPrompt: false, cvText: "", huntMode: false, careerSignals: [], huntActions: DEFAULT_ACTIONS, careerGoalDraft: "", referrals: [], mentorRequests: [], careerCircles: [{ id: "fintech-leaders", name: "FinTech Leaders", focus: "Payments, financial technology and leadership", members: 128 }, { id: "global-pm", name: "Global Product Leaders", focus: "Product strategy and international careers", members: 214 }, { id: "global-hunters", name: "Global Job Hunters", focus: "International opportunity discovery", members: 96 }], lastAgentRunAt: null,
  register: u => { const email = u.email.trim().toLowerCase(); if (!email || !u.password || !u.name) return { ok: false, error: "All fields are required" }; if (get().users.some(x => x.email === email)) return { ok: false, error: "Email already registered" }; set({ users: [...get().users, { ...u, email }], sessionEmail: email, view: "dashboard" }); return { ok: true }; },
  login: (email, password) => { const user = get().users.find(u => u.email.toLowerCase() === email.trim().toLowerCase()); if (!user || user.password !== password) return { ok: false, error: "Invalid email or password" }; set({ sessionEmail: user.email, view: "dashboard" }); return { ok: true }; },
  logout: () => set({ sessionEmail: null, view: "dashboard" }), setView: view => set({ view }), setFilters: f => set({ filters: { ...get().filters, ...f } }),
  applyTo: jobId => { if (get().applications.some(a => a.jobId === jobId)) return; set({ applications: [{ id: `a-${Date.now()}`, jobId, status: "applied", appliedAt: new Date().toISOString().slice(0, 10) }, ...get().applications] }); },
  setStatus: (id, status) => set({ applications: get().applications.map(a => a.id === id ? { ...a, status } : a) }), toggleSaveJob: jobId => { const ids = get().savedJobIds; set({ savedJobIds: ids.includes(jobId) ? ids.filter(x => x !== jobId) : [...ids, jobId] }); },
  saveCurrentSearch: () => { const f = get().filters; set({ savedSearches: [{ id: `ss-${Date.now()}`, query: [f.role, f.industry, f.location].filter(Boolean).join(" · "), ...f, createdAt: new Date().toISOString().slice(0, 10) }, ...get().savedSearches] }); }, removeSavedSearch: id => set({ savedSearches: get().savedSearches.filter(s => s.id !== id) }),
  updateProfile: p => { const email = get().sessionEmail; if (!email) return; set({ users: get().users.map(u => u.email === email ? { ...u, ...p } : u) }); }, setDemoOpen: demoOpen => set({ demoOpen }), setAdminPrompt: adminPrompt => set({ adminPrompt }), setCvText: cvText => set({ cvText }),
  setHuntMode: huntMode => set({ huntMode }), completeHuntAction: id => set({ huntActions: get().huntActions.map(a => a.id === id ? { ...a, completed: true } : a) }), addCareerSignal: s => set({ careerSignals: [{ ...s, id: `signal-${Date.now()}`, createdAt: new Date().toISOString() }, ...get().careerSignals] }), setCareerGoalDraft: careerGoalDraft => set({ careerGoalDraft }),
  requestReferral: (jobId, note) => set({ referrals: [{ id: `ref-${Date.now()}`, jobId, note, status: "requested", createdAt: new Date().toISOString() }, ...get().referrals] }), requestMentor: goal => set({ mentorRequests: [{ id: `mentor-${Date.now()}`, goal, status: "open", createdAt: new Date().toISOString() }, ...get().mentorRequests] }), setAgentRun: () => set({ lastAgentRunAt: new Date().toISOString() }),
}), { name: "gotecha-v2" }));

export function useSessionUser() { return useGotcha(s => s.users.find(u => u.email === s.sessionEmail) ?? null); }
