import { useMemo, useState } from "react";
import {
  ArrowRight,
  BarChart3,
  BriefcaseBusiness,
  CheckCircle2,
  ChevronRight,
  CircleDollarSign,
  FileSearch,
  Globe2,
  MapPin,
  Radar,
  Search,
  Sparkles,
  Target,
  TrendingUp,
  UserRound,
  Zap,
} from "lucide-react";
import { JOBS, type Job } from "@/lib/data";
import { applicationAnalytics, careerHuntScore, mobilityAssessment, scoreOpportunity } from "@/lib/careerIntelligence";
import { useGotcha, useSessionUser } from "@/lib/store";
import { cn } from "@/lib/utils";

const surface = "rounded-2xl border border-border/80 bg-card/95 shadow-[0_14px_40px_rgba(0,0,0,0.16)]";

function SectionHeading({ icon: Icon, eyebrow, title, action, onAction }: { icon: typeof Search; eyebrow?: string; title: string; action?: string; onAction?: () => void }) {
  return <div className="mb-4 flex items-start justify-between gap-3"><div>{eyebrow && <p className="mb-1 text-[9px] font-semibold uppercase tracking-[0.2em] text-primary-3">{eyebrow}</p>}<h2 className="flex items-center gap-2 text-sm font-semibold tracking-tight text-fg"><Icon className="size-4 text-primary-3" />{title}</h2></div>{action && onAction && <button type="button" onClick={onAction} className="inline-flex items-center gap-1 text-[10px] font-semibold text-primary-3 hover:text-fg">{action}<ArrowRight className="size-3" /></button>}</div>;
}

function MetricCard({ label, value, detail, icon: Icon, tone = "text-fg", onClick }: { label: string; value: string | number; detail: string; icon: typeof Search; tone?: string; onClick?: () => void }) {
  const Tag = onClick ? "button" : "div";
  return <Tag type={onClick ? "button" : undefined} onClick={onClick} className={cn("w-full text-left", surface, "p-4 transition duration-200", onClick && "cursor-pointer hover:-translate-y-0.5 hover:border-primary/50 hover:bg-card-2")}><div className="flex items-start justify-between gap-2"><span className="flex size-8 items-center justify-center rounded-lg border border-border bg-surface"><Icon className="size-4 text-primary-3" /></span><TrendingUp className="size-3.5 text-emerald-400/80" /></div><p className="mt-3 text-[9px] font-semibold uppercase tracking-[0.16em] text-muted">{label}</p><p className={cn("mt-0.5 text-2xl font-bold tabular-nums", tone)}>{value}</p><p className="mt-1 text-[10px] leading-4 text-subtle">{detail}</p></Tag>;
}

function Funnel({ analytics }: { analytics: ReturnType<typeof applicationAnalytics> }) {
  const stages = [{ label: "Discovered", value: Math.max(JOBS.length, analytics.total), width: 100, tone: "bg-primary" }, { label: "Applied", value: analytics.total, width: Math.max(12, Math.min(78, analytics.total * 8)), tone: "bg-cyan-400" }, { label: "Interview", value: analytics.interviews, width: Math.max(7, Math.min(58, analytics.interviews * 16)), tone: "bg-violet-400" }, { label: "Offer", value: analytics.offers, width: Math.max(4, Math.min(42, analytics.offers * 22)), tone: "bg-emerald-400" }];
  return <div className="space-y-2.5">{stages.map((stage) => <div key={stage.label} className="grid grid-cols-[72px_minmax(0,1fr)_30px] items-center gap-2"><span className="text-[10px] text-muted">{stage.label}</span><div className="h-2 overflow-hidden rounded-full bg-bg"><div className={cn("h-full rounded-full transition-all", stage.tone)} style={{ width: `${stage.width}%` }} /></div><span className="text-right text-[10px] font-semibold tabular-nums text-fg">{stage.value}</span></div>)}</div>;
}

function CareerMap({ onOpen }: { onOpen: () => void }) {
  const points = [[17, 39, "bg-emerald-400", "India"], [29, 27, "bg-cyan-400", "Singapore"], [48, 25, "bg-violet-400", "Europe"], [59, 42, "bg-amber-400", "GCC"], [71, 32, "bg-emerald-400", "APAC"], [81, 45, "bg-rose-400", "US"], [88, 61, "bg-cyan-400", "Canada"]] as const;
  return <button type="button" onClick={onOpen} className="group relative h-[250px] w-full overflow-hidden rounded-xl border border-border/70 bg-[#07111c] text-left transition hover:border-primary/50"><div className="absolute inset-0 opacity-50" style={{ backgroundImage: "linear-gradient(rgba(90,140,180,.08) 1px, transparent 1px), linear-gradient(90deg, rgba(90,140,180,.08) 1px, transparent 1px)", backgroundSize: "28px 28px" }} /><svg viewBox="0 0 100 60" className="absolute inset-0 h-full w-full opacity-80" preserveAspectRatio="none" aria-hidden><path d="M8 20 C17 11 27 13 34 20 C40 25 43 20 49 17 C58 12 67 14 76 21 C84 27 92 25 96 33" fill="none" stroke="rgba(88,130,170,.28)" strokeWidth=".7" /><path d="M10 36 C21 29 30 34 40 31 C50 28 59 34 67 30 C78 25 88 35 96 40" fill="none" stroke="rgba(88,130,170,.22)" strokeWidth=".6" /><path d="M17 39 Q34 16 48 25 T81 45" fill="none" stroke="#22d3ee" strokeWidth=".55" strokeDasharray="2 1.5" opacity=".7" /></svg>{points.map(([left, top, tone, label]) => <span key={label} className="absolute" style={{ left: `${left}%`, top: `${top}%` }}><span className={cn("absolute -inset-2 animate-pulse rounded-full opacity-20", tone)} /><span className={cn("relative block size-2 rounded-full ring-2 ring-bg/50", tone)} /><span className="absolute left-3 top-0 whitespace-nowrap text-[9px] text-slate-400">{label}</span></span>)}<div className="absolute bottom-3 left-3 right-3 flex items-center justify-between rounded-lg border border-white/10 bg-black/25 px-3 py-2 backdrop-blur-sm"><span className="text-[10px] text-slate-300"><Globe2 className="mr-1 inline size-3 text-primary-3" />Global opportunity density</span><span className="text-[9px] font-semibold text-primary-3 group-hover:text-fg">Explore map →</span></div></button>;
}

export function GotchaCareerDashboard({ onOpenJob }: { onOpenJob: (j: Job) => void }) {
  const user = useSessionUser();
  const applications = useGotcha((s) => s.applications);
  const savedJobIds = useGotcha((s) => s.savedJobIds);
  const cvText = useGotcha((s) => s.cvText);
  const careerEvents = useGotcha((s) => s.careerEvents);
  const setView = useGotcha((s) => s.setView);
  const setFilters = useGotcha((s) => s.setFilters);
  const [query, setQuery] = useState("");
  const analytics = applicationAnalytics(applications);
  const huntScore = careerHuntScore(user, applications);
  const mobility = user ? mobilityAssessment(user) : { score: 0, markets: [], factors: [] };
  const topMatches = useMemo(() => user ? [...JOBS].map((job) => ({ job, score: scoreOpportunity(job, user).overall })).sort((a, b) => b.score - a.score).slice(0, 4) : [], [user]);
  const targetMarket = user?.targetCountries?.[0] ?? "Global";
  const recentApps = applications.slice(0, 4).map((a) => ({ app: a, job: JOBS.find((j) => j.id === a.jobId) })).filter((x): x is { app: (typeof applications)[number]; job: Job } => Boolean(x.job));

  function launchSearch() { const clean = query.trim(); if (clean) setFilters({ role: clean }); setView("search"); }

  return <div className="min-w-0 space-y-5">
    <section className="relative overflow-hidden rounded-2xl border border-primary/20 bg-linear-to-br from-card via-card to-primary/5 p-5 md:p-6"><div className="pointer-events-none absolute -right-20 -top-24 size-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-primary-3">GOTCHA INTELLIGENCE CENTER</p><h1 className="mt-1 text-2xl font-semibold tracking-tight md:text-3xl">Good morning{user?.name ? `, ${user.name.split(" ")[0]}` : ""}.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted">Your AI-powered career command center — discover better-fit opportunities, understand your market, and move the right applications forward.</p></div><button type="button" onClick={() => setView("hunt")} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-semibold glow-primary">Launch Hunt Mode <Zap className="size-3.5" /></button></div><div className="relative mt-5 flex flex-col overflow-hidden rounded-xl border border-border bg-bg/60 md:flex-row"><div className="flex min-w-0 flex-1 items-center gap-3 px-4 py-3"><Search className="size-4 shrink-0 text-primary-3" /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") launchSearch(); }} placeholder="Ask Gotcha to find your next opportunity…" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-subtle" /></div><button type="button" onClick={launchSearch} className="m-1 rounded-lg bg-primary px-5 py-2 text-xs font-semibold">AI Search <ArrowRight className="ml-1 inline size-3" /></button></div></section>

    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard label="AI Match Pool" value={JOBS.length} detail="Current opportunities in your live dataset" icon={Radar} tone="text-cyan-300" onClick={() => setView("opportunities")} /><MetricCard label="Career Hunt Score" value={huntScore || "—"} detail="Profile + activity readiness score" icon={Target} tone="text-violet-300" onClick={() => setView("profile")} /><MetricCard label="Applications" value={analytics.total} detail={`${analytics.followUpsDue} follow-ups currently due`} icon={BriefcaseBusiness} tone="text-amber-300" onClick={() => setView("applications")} /><MetricCard label="Saved Opportunities" value={savedJobIds.length} detail="Roles you want to revisit" icon={CheckCircle2} tone="text-emerald-300" onClick={() => setView("saved")} /></div>

    <section className={cn(surface, "p-5")}><SectionHeading icon={Sparkles} eyebrow="AI TALENT ACQUISITION SEARCH" title="Find roles that fit your career, not just your keywords" action="Open AI Job Search" onAction={() => setView("search")} /><div className="grid gap-4 lg:grid-cols-[1.4fr_.8fr_.8fr]"><button type="button" onClick={() => setView("search")} className="group rounded-xl border border-primary/20 bg-linear-to-br from-primary/10 to-transparent p-4 text-left transition hover:border-primary/50"><div className="flex items-center justify-between"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/15"><Sparkles className="size-4 text-primary-3" /></span><ChevronRight className="size-4 text-muted transition group-hover:translate-x-1 group-hover:text-primary-3" /></div><p className="mt-4 text-sm font-semibold">Natural-language talent search</p><p className="mt-1 text-xs leading-5 text-muted">Describe your ideal role, geography, seniority and work model. Gotcha carries your preferences into the existing AI search engine.</p><span className="mt-4 inline-flex rounded-full border border-border bg-surface px-2.5 py-1 text-[9px] font-semibold uppercase tracking-wider text-primary-3">{user?.targetRoles?.[0] ?? "Build your target"}</span></button><div className="rounded-xl border border-border bg-surface p-4"><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-muted">Target market</p><p className="mt-2 text-lg font-semibold">{targetMarket}</p><p className="mt-1 text-[10px] text-subtle">Mobility readiness <span className="font-semibold text-fg">{mobility.score || "—"}/100</span></p><div className="mt-3 h-1.5 rounded-full bg-bg"><div className="h-full rounded-full bg-primary" style={{ width: `${mobility.score || 0}%` }} /></div></div><div className="rounded-xl border border-border bg-surface p-4"><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-muted">Search activity</p><p className="mt-2 text-lg font-semibold">{careerEvents.length}</p><p className="mt-1 text-[10px] text-subtle">Career events captured across your Gotcha journey.</p><button type="button" onClick={() => setView("saved")} className="mt-3 text-[10px] font-semibold text-primary-3">Review saved searches →</button></div></div></section>

    <div className="grid gap-5 xl:grid-cols-2"><section className={cn(surface, "p-5")}><SectionHeading icon={Sparkles} eyebrow="AI CAREER COACH & INSIGHT" title="Your next best career move" action="Open Coach" onAction={() => setView("coach")} /><div className="rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-primary/15"><Sparkles className="size-4 text-primary-3" /></span><div className="min-w-0"><p className="text-sm font-semibold">{user?.targetRoles?.[0] ? `Prioritize ${user.targetRoles[0]} roles` : "Complete your profile to unlock personalized guidance"}</p><p className="mt-1 text-xs leading-5 text-muted">{analytics.total === 0 ? "Start with a focused application rather than volume. Gotcha will use your profile and role fit to guide the hunt." : `You have ${analytics.total} tracked application${analytics.total === 1 ? "" : "s"}. Your current response rate is ${analytics.responseRate}%; use the Coach to decide what to improve next.`}</p></div></div><button type="button" onClick={() => setView("coach")} className="mt-4 rounded-lg border border-border bg-surface px-3 py-2 text-[10px] font-semibold hover:border-primary/50">Ask AI Career Coach <ArrowRight className="ml-1 inline size-3" /></button></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-lg bg-surface p-3"><p className="text-[9px] uppercase text-muted">Response</p><p className="mt-1 text-lg font-bold text-amber-300">{analytics.responseRate}%</p></div><div className="rounded-lg bg-surface p-3"><p className="text-[9px] uppercase text-muted">Interview</p><p className="mt-1 text-lg font-bold text-violet-300">{analytics.interviewRate}%</p></div><div className="rounded-lg bg-surface p-3"><p className="text-[9px] uppercase text-muted">Offer</p><p className="mt-1 text-lg font-bold text-emerald-300">{analytics.offerRate}%</p></div></div></section><section className={cn(surface, "p-5")}><SectionHeading icon={Globe2} eyebrow="GLOBAL CAREER MAP & PREDICTIVE PIPELINE" title="Where your career can move next" action="Open Global Intelligence" onAction={() => setView("network")} /><CareerMap onOpen={() => setView("network")} /><div className="mt-3 flex flex-wrap items-center gap-2 text-[9px] text-muted"><span className="rounded-full border border-border px-2 py-1">{mobility.markets.length || 1} target markets</span><span className="rounded-full border border-border px-2 py-1">{JOBS.filter((j) => j.work === "Remote").length} remote roles</span><span className="rounded-full border border-border px-2 py-1">Predictive fit enabled</span></div></section></div>

    <section className={cn(surface, "p-5")}><SectionHeading icon={BriefcaseBusiness} eyebrow="TOP CURATED OPPORTUNITIES" title="High-fit roles worth your attention" action="View all opportunities" onAction={() => setView("opportunities")} /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{topMatches.map(({ job, score }) => <button key={job.id} type="button" onClick={() => onOpenJob(job)} className="group rounded-xl border border-border bg-surface p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/50 hover:bg-card-2"><div className="flex items-start justify-between gap-2"><span className="flex size-9 items-center justify-center rounded-lg text-xs font-bold" style={{ background: job.logoBg }}>{job.logo}</span><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] font-bold text-emerald-300">{score}% fit</span></div><p className="mt-3 line-clamp-2 text-sm font-semibold">{job.title}</p><p className="mt-1 text-[10px] text-muted">{job.company}</p><p className="mt-3 flex items-center gap-1 text-[10px] text-subtle"><MapPin className="size-3" />{job.location}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-subtle"><CircleDollarSign className="size-3" />{job.salary}</p><span className="mt-4 inline-flex items-center text-[9px] font-semibold text-primary-3">View role <ArrowRight className="ml-1 size-3 transition group-hover:translate-x-1" /></span></button>)}</div></section>

    <div className="grid gap-5 lg:grid-cols-2"><section className={cn(surface, "p-5")}><SectionHeading icon={FileSearch} eyebrow="JOB MATCH & CV ANALYSIS" title="Make every application stronger" action="Open CV Intelligence" onAction={() => setView("cv")} /><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setView("cv")} className="rounded-xl border border-border bg-surface p-4 text-left transition hover:border-primary/50"><div className="flex items-center justify-between"><FileSearch className="size-5 text-primary-3" /><span className={cn("text-[9px] font-semibold", cvText ? "text-emerald-300" : "text-amber-300")}>{cvText ? "PROFILE READY" : "ACTION NEEDED"}</span></div><p className="mt-3 text-sm font-semibold">CV Intelligence</p><p className="mt-1 text-[10px] leading-4 text-muted">{cvText ? "Your CV is available for role alignment and variant analysis." : "Upload or build your CV so Gotcha can align it to target roles."}</p></button><button type="button" onClick={() => setView("opportunities")} className="rounded-xl border border-border bg-surface p-4 text-left transition hover:border-primary/50"><div className="flex items-center justify-between"><BarChart3 className="size-5 text-primary-3" /><span className="text-[9px] font-semibold text-emerald-300">LIVE</span></div><p className="mt-3 text-sm font-semibold">Match analysis</p><p className="mt-1 text-[10px] leading-4 text-muted">Compare fit signals across skills, experience, location, work model and growth.</p></button></div></section><section className={cn(surface, "p-5")}><SectionHeading icon={BarChart3} eyebrow="RECENT ACTIVITY / FUNNEL" title="Your hunt in motion" action="Open Applications" onAction={() => setView("applications")} /><div className="grid gap-4 sm:grid-cols-[1.05fr_.95fr]"><Funnel analytics={analytics} /><div className="space-y-2">{recentApps.length ? recentApps.map(({ app, job }) => <button key={app.id} type="button" onClick={() => onOpenJob(job)} className="flex w-full items-center gap-2 rounded-lg border border-border bg-surface p-2.5 text-left hover:border-primary/40"><span className="flex size-7 shrink-0 items-center justify-center rounded-md text-[9px] font-bold" style={{ background: job.logoBg }}>{job.logo}</span><span className="min-w-0 flex-1"><span className="block truncate text-[10px] font-semibold">{job.company} · {job.title}</span><span className="text-[9px] capitalize text-muted">{app.status} · {app.appliedAt}</span></span><ChevronRight className="size-3 text-subtle" /></button>) : <div className="rounded-lg border border-dashed border-border p-4"><p className="text-xs font-medium">No applications yet</p><p className="mt-1 text-[10px] leading-4 text-muted">Open Opportunities, choose a role, and use the existing Apply flow to start your funnel.</p><button type="button" onClick={() => setView("opportunities")} className="mt-3 text-[10px] font-semibold text-primary-3">Find your first match →</button></div>}</div></div></section></div>

    <section className="overflow-hidden rounded-2xl border border-primary/20 bg-linear-to-r from-primary/10 via-card to-card p-6"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-primary-3">THE GOTCHA DIFFERENCE</p><h2 className="mt-1 text-xl font-semibold">Why Professionals Choose GOTCHA</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-muted">One intelligence layer connects discovery, matching, CV strategy, career coaching, global mobility and application progress — without creating duplicate workflows.</p></div><button type="button" onClick={() => setView("hunt")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-primary/40 bg-primary/10 px-4 py-2.5 text-xs font-semibold text-primary-3 hover:bg-primary/20">Keep hunting <ArrowRight className="size-3.5" /></button></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[{ icon: Zap, t: "AI-Powered Matching", d: "Fit beyond keywords", view: "search" }, { icon: Globe2, t: "Global Intelligence", d: "Markets and mobility", view: "network" }, { icon: FileSearch, t: "CV Intelligence", d: "Role-specific positioning", view: "cv" }, { icon: UserRound, t: "End-to-End Support", d: "Coach to application", view: "coach" }].map((x) => <button type="button" key={x.t} onClick={() => setView(x.view as Parameters<typeof setView>[0])} className="rounded-xl border border-border bg-surface/80 p-3 text-left hover:border-primary/40"><x.icon className="size-4 text-primary-3" /><p className="mt-2 text-[10px] font-semibold">{x.t}</p><p className="mt-0.5 text-[9px] text-subtle">{x.d}</p></button>)}</div></section>
  </div>;
}
